GET http://localhost:5000/api/fruits

###

POST http://localhost:5000/api/fruits
Content-Type: application/json

{
    "name": "Carrot",
    "amount": 5,
    "info": "Not a Fruit"
}

###

DELETE http://localhost:5000/api/fruits/5fba4ab559003a0c88bbd503

###

PUT http://localhost:5000/api/fruits/5fba4aaa59003a0c88bbd502
Content-Type: application/json

{
    "name": "Banana",
    "amount": 3,
    "info": "Yellow Gentleman"
}